# Generated by Django 6.0.5 on 2026-05-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejercicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCoach',
            fields=[
                ('id_cliente_coach', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('id_cliente', models.ForeignKey(db_column='ID_CLIENTE', on_delete=django.db.models.deletion.CASCADE, related_name='coach_cliente', to='usuarios.usuario')),
                ('id_coach', models.ForeignKey(db_column='ID_COACH', on_delete=django.db.models.deletion.CASCADE, related_name='clientes_coach', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'CLIENTE_COACH',
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('objetivo', models.CharField(blank=True, max_length=250, null=True)),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('id_coach', models.ForeignKey(db_column='ID_COACH', on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_creadas', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'RUTINAS',
            },
        ),
        migrations.CreateModel(
            name='DetalleRutina',
            fields=[
                ('id_detalle_rutina', models.IntegerField(primary_key=True, serialize=False)),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('descanso_segundos', models.IntegerField()),
                ('orden_ejercicio', models.IntegerField()),
                ('id_ejercicio', models.ForeignKey(db_column='ID_EJERCICIO', on_delete=django.db.models.deletion.CASCADE, to='ejercicios.ejercicio')),
                ('id_rutina', models.ForeignKey(db_column='ID_RUTINA', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rutinas.rutina')),
            ],
            options={
                'db_table': 'DETALLE_RUTINA',
            },
        ),
        migrations.CreateModel(
            name='AsignacionRutina',
            fields=[
                ('id_asignacion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('id_cliente', models.ForeignKey(db_column='ID_CLIENTE', on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_asignadas', to='usuarios.usuario')),
                ('id_rutina', models.ForeignKey(db_column='ID_RUTINA', on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
            ],
            options={
                'db_table': 'ASIGNACION_RUTINA',
            },
        ),
    ]
