# Generated by Django 6.0.5 on 2026-05-27 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejercicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('objetivo', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('id_coach', models.ForeignKey(blank=True, db_column='ID_COACH', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'RUTINA',
            },
        ),
        migrations.CreateModel(
            name='DetalleRutina',
            fields=[
                ('id_detalle_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('series', models.IntegerField(blank=True, null=True)),
                ('repeticiones', models.IntegerField(blank=True, null=True)),
                ('descanso_segundos', models.IntegerField(blank=True, null=True)),
                ('orden_ejercicio', models.IntegerField(blank=True, null=True)),
                ('id_ejercicio', models.ForeignKey(blank=True, db_column='ID_EJERCICIO', null=True, on_delete=django.db.models.deletion.CASCADE, to='ejercicios.ejercicio')),
                ('id_rutina', models.ForeignKey(blank=True, db_column='ID_RUTINA', null=True, on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
            ],
            options={
                'db_table': 'DETALLE_RUTINA',
            },
        ),
        migrations.CreateModel(
            name='AsignacionRutina',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='ID_CLIENTE', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_asignadas', to='usuarios.usuario')),
                ('id_rutina', models.ForeignKey(blank=True, db_column='ID_RUTINA', null=True, on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
            ],
            options={
                'db_table': 'ASIGNACION_RUTINA',
            },
        ),
    ]
