# Generated by Django 6.0.5 on 2026-05-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
