# Generated by Django 6.0.5 on 2026-05-27 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMedida',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_grasa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('masa_muscular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cuello', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cadera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pecho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('brazo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pierna', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_medicion', models.DateField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='ID_CLIENTE', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'HISTORIAL_MEDIDA',
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_grasa_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('masa_muscular_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('id_cliente', models.OneToOneField(db_column='ID_CLIENTE', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'MEDIDA',
            },
        ),
    ]
