# Generated by Django 6.0.5 on 2026-05-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMedidas',
            fields=[
                ('id_historial', models.IntegerField(primary_key=True, serialize=False)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_grasa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('masa_muscular', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cuello', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cintura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cadera', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pecho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('brazo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pierna', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_medicion', models.DateField()),
                ('id_cliente', models.ForeignKey(db_column='ID_CLIENTE', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'HISTORIAL_MEDIDAS',
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.IntegerField(primary_key=True, serialize=False)),
                ('peso_actual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_grasa_actual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('masa_muscular_actual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_actualizacion', models.DateField()),
                ('id_cliente', models.ForeignKey(db_column='ID_CLIENTE', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'MEDIDAS',
            },
        ),
    ]
