# Generated by Django 6.0.5 on 2026-05-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id_canton', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CANTONES',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PROVINCIAS',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id_distrito', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_canton', models.ForeignKey(db_column='ID_CANTON', on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='ubicaciones.canton')),
            ],
            options={
                'db_table': 'DISTRITOS',
            },
        ),
        migrations.AddField(
            model_name='canton',
            name='id_provincia',
            field=models.ForeignKey(db_column='ID_PROVINCIA', on_delete=django.db.models.deletion.CASCADE, related_name='cantones', to='ubicaciones.provincia'),
        ),
    ]
