# Generated by Django 6.0.5 on 2026-05-27 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEjercicio',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'CATEGORIA_EJERCICIO',
            },
        ),
        migrations.CreateModel(
            name='DificultadEjercicio',
            fields=[
                ('id_dificultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'DIFICULTAD_EJERCICIO',
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('calorias_estimadas', models.IntegerField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='ID_CATEGORIA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ejercicios.categoriaejercicio')),
                ('id_dificultad', models.ForeignKey(blank=True, db_column='ID_DIFICULTAD', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ejercicios.dificultadejercicio')),
            ],
            options={
                'db_table': 'EJERCICIO',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_imagen', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('id_ejercicio', models.ForeignKey(blank=True, db_column='ID_EJERCICIO', null=True, on_delete=django.db.models.deletion.CASCADE, to='ejercicios.ejercicio')),
            ],
            options={
                'db_table': 'IMAGEN',
            },
        ),
    ]
