# Generated by Django 6.0.5 on 2026-05-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEjercicio',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'CATEGORIAS_EJERCICIO',
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('nivel_dificultad', models.CharField(blank=True, max_length=50, null=True)),
                ('calorias_estimadas', models.IntegerField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(db_column='ID_CATEGORIA', on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='ejercicios.categoriaejercicio')),
            ],
            options={
                'db_table': 'EJERCICIOS',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.IntegerField(primary_key=True, serialize=False)),
                ('ruta_imagen', models.CharField(max_length=500)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('id_ejercicio', models.ForeignKey(db_column='ID_EJERCICIO', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ejercicios.ejercicio')),
            ],
            options={
                'db_table': 'IMAGENES',
            },
        ),
    ]
