# Generated by Django 6.0.5 on 2026-05-27 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion_exacta', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('id_distrito', models.ForeignKey(db_column='ID_DISTRITO', on_delete=django.db.models.deletion.RESTRICT, to='ubicaciones.distrito')),
            ],
            options={
                'db_table': 'SUCURSAL',
            },
        ),
    ]
