# Generated by Django 6.0.5 on 2026-05-27 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ROL',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'SEXO',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_distrito', models.ForeignKey(blank=True, db_column='ID_DISTRITO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicaciones.distrito')),
                ('id_rol', models.ForeignKey(blank=True, db_column='ID_ROL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.rol')),
                ('id_sexo', models.ForeignKey(blank=True, db_column='ID_SEXO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.sexo')),
                ('id_sucursal', models.ForeignKey(blank=True, db_column='ID_SUCURSAL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sucursales.sucursal')),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='ClienteCoach',
            fields=[
                ('id_cliente_coach', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='ID_CLIENTE', on_delete=django.db.models.deletion.CASCADE, related_name='coaches_asignados', to='usuarios.usuario')),
                ('id_coach', models.ForeignKey(db_column='ID_COACH', on_delete=django.db.models.deletion.CASCADE, related_name='clientes_asignados', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'CLIENTE_COACH',
            },
        ),
    ]
