# Generated by Django 6.0.5 on 2026-05-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150)),
                ('contrasena', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('direccion_exacta', models.CharField(blank=True, max_length=250, null=True)),
                ('id_distrito', models.ForeignKey(blank=True, db_column='ID_DISTRITO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicaciones.distrito')),
                ('id_sucursal', models.ForeignKey(blank=True, db_column='ID_SUCURSAL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sucursales.sucursal')),
            ],
            options={
                'db_table': 'USUARIOS',
            },
        ),
    ]
